"use client";

interface Item {
  medicine?: string;
  dosage?: string;
  frequency?: string;
  duration?: string;
  notes?: string;
}

export default function PrescriptionCard({
  items,
  doctorName,
  patientName,
  date,
}: {
  items: Item[];
  doctorName?: string;
  patientName?: string;
  date?: string;
}) {
  if (!items || items.length === 0) return null;

  const handlePrint = () => {
    const w = window.open("", "_blank", "width=800,height=600");
    if (!w) return;
    const rows = items
      .map(
        (it) => `
          <tr>
            <td>${escapeHtml(it.medicine || "")}</td>
            <td>${escapeHtml(it.dosage || "")}</td>
            <td>${escapeHtml(it.frequency || "")}</td>
            <td>${escapeHtml(it.duration || "")}</td>
            <td>${escapeHtml(it.notes || "")}</td>
          </tr>`
      )
      .join("");
    w.document.write(`
      <!doctype html>
      <html>
        <head>
          <title>Prescription</title>
          <style>
            body { font-family: -apple-system, system-ui, sans-serif; padding: 32px; color: #1f2937; }
            h1 { color: #0d9488; margin: 0 0 4px; }
            .meta { color: #6b7280; font-size: 13px; margin-bottom: 24px; }
            table { width: 100%; border-collapse: collapse; margin-top: 12px; }
            th, td { border: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; font-size: 14px; }
            th { background: #f0fdfa; color: #115e59; }
            .footer { margin-top: 32px; font-size: 12px; color: #9ca3af; }
          </style>
        </head>
        <body>
          <h1>HealthPro · Prescription</h1>
          <div class="meta">
            ${patientName ? `Patient: <b>${escapeHtml(patientName)}</b><br>` : ""}
            ${doctorName ? `Prescribed by: <b>${escapeHtml(doctorName)}</b><br>` : ""}
            ${date ? `Date: ${escapeHtml(date)}` : ""}
          </div>
          <table>
            <thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Notes</th></tr></thead>
            <tbody>${rows}</tbody>
          </table>
          <p class="footer">Generated by HealthPro · Not a substitute for the original prescription.</p>
          <script>window.onload = () => window.print();</script>
        </body>
      </html>
    `);
    w.document.close();
  };

  return (
    <div className="mt-3 border border-emerald-200 bg-emerald-50/40 rounded-lg p-3">
      <div className="flex items-center justify-between mb-2">
        <p className="text-sm font-semibold text-emerald-800">Prescription</p>
        <button
          onClick={handlePrint}
          className="text-xs px-2.5 py-1 text-emerald-700 bg-white border border-emerald-300 rounded hover:bg-emerald-50"
        >
          Print / PDF
        </button>
      </div>
      <ul className="space-y-1.5">
        {items.map((it, i) => (
          <li key={i} className="text-sm text-gray-800">
            <span className="font-medium">{it.medicine || "—"}</span>
            {it.dosage && <span className="text-gray-500"> · {it.dosage}</span>}
            {it.frequency && <span className="text-gray-500"> · {it.frequency}</span>}
            {it.duration && <span className="text-gray-500"> · {it.duration}</span>}
            {it.notes && <span className="block text-xs text-gray-500 ml-1 italic">{it.notes}</span>}
          </li>
        ))}
      </ul>
    </div>
  );
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
